pipeline {
   agent any

   stages {
     stage('Polling SCM' ) {
         steps {
            echo 'Cloning code from remote repository'
	    sh '''
            cd /tmp/
	    mkdir icon || 'true'
            cd icon
            git clone https://github.com/deji-bit/myweatherapp.git
            '''
      	 }  
       }
      stage('Compile' ) {
         steps {
            echo 'Compiling code...'
	    sh '''
            cd /tmp/icon/myweatherapp
            mvn clean package
            '''
      	 }  
       }
      stage('Build' ) {
         steps {
            echo 'Preparing for deployment to remote node'
            sh '''
            sudo ssh -i /tmp/first_keys ec2-user@35.178.83.93 'rm -r /tmp/weather-app-0.0.1-SNAPSHOT.jar' || 'true'
            sudo scp -v -o StrictHostKeyChecking=no -i /tmp/first_keys /tmp/icon/myweatherapp/target/weather-app-0.0.1-SNAPSHOT.jar ec2-user@35.178.83.93:/tmp/
            '''
      	 }
       }
      stage('Deploy' ) {
         steps {
            echo 'Deploying code to non-active node'
	    sh '''
	    sudo ssh -i /tmp/first_keys ec2-user@35.178.83.93 '
            cd /tmp/
            java -jar weather-app-0.0.1-SNAPSHOT.jar -Dapp.weather.locations=Nigeria/Lagos,Nigeria/Kano &
            exit '
            pwd
            '''
      	 }
       }
      stage('Cleanup' ) {
         steps {
            echo 'Removing used files and folders'
	    sh '''
	    sudo rm -rf /tmp/icon/
            '''
      	 }
       }
    }  
}
